name: Scheduled Workflow Experiment

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-on-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Print time
        run: |
          echo "Scheduled workflow running"
          date
